### ISSUE TITLE
How to close a WebSocket connection? After calling destroy(), the connection still runs normally

### ISSUE THREAD

**Issue by zhang22113** [phoboslab/jsmpeg#433] opened 2024-12-03 07:02 UTC

**Comment by phoboslab** [comment] 2024-12-03 09:04
Can't reproduce.

player.destroy() calls [this.source.destroy()](https://github.com/phoboslab/jsmpeg/blob/master/src/player.js#L163), which in turn calls [this.socket.close()](https://github.com/phoboslab/jsmpeg/blob/master/src/websocket.js#L34). So this should work as intended. And for me, it does:

```js
player.destroy();
player.source.socket.readyState // 3 (WebSocket.CLOSED)
```

**Comment by zhang22113** [comment] 2024-12-03 09:11
> 無法重現。
> 
> player.destroy() 调用[this.source.destroy()](https://github.com/phoboslab/jsmpeg/blob/master/src/player.js#L163)，后者又调用[this.socket.close()](https://github.com/phoboslab/jsmpeg/blob/master/src/websocket.js#L34)。所以这应该可以按预期工作。对我来说，它确实如此：
> 
> ```js
> player.destroy();
> player.source.socket.readyState // 3 (WebSocket.CLOSED)
> ```

<template>
  <div>
    <h1>AI识别</h1>
    
    <button @click="togglePlayPause">{{ isPaused ? '播放' : '暂停' }}</button>

    
    
    

    
    <button @click="destroyT">停止</button>
    
    <label>播放时长: {{ formattedDuration }}</label>

    <div style="border: 2px white solid">
      <canvas ref="jsmpegCanvas" style="width: 800px; height: 600px"></canvas>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const jsmpegCanvas = ref(null)
let player = null // 用于保存 JSMpeg.Player 实例
const isPaused = ref(false) // 用于控制按钮的状态
const volume = ref(1) // 控制音量，范围是 0 到 1
let duration = ref(0) // 用于保存视频的播放时长
let timer = ref(null)
// 格式化时长为 "天 天数 小时 小时数 分钟 分钟数 秒 秒数" 的格式
function formatDuration(seconds) {
  if (isNaN(seconds)) return '0s'
  const days = Math.floor(seconds / (24 * 3600))
  seconds %= 24 * 3600
  const hours = Math.floor(seconds / 3600)
  seconds %= 3600
  const minutes = Math.floor(seconds / 60)
  const secs = (seconds % 60).toFixed(2) // 保留两位小数

  let result = ''
  if (days > 0) result += `${days}天 `
  if (hours > 0) result += `${hours}小时 `
  if (minutes > 0) result += `${minutes}分钟 `
  result += `${secs}秒`

  return result
}

onMounted(() => {
  getVideos()

  // 定时更新播放进度
  timer.value = setInterval(() => {
    if (player) {
      duration.value = player.currentTime
    }
  }, 1000)
})
onUnmounted(() => {
  // 组件销毁时清除定时器
  clearInterval(timer);
  // 停止播放器并释放资源
  if (player) {
    if (player.source && player.source.socket) {
      console.log("触发销毁")
      player.Source.WSSource.Close()
      player.source.socket.close(); // 直接调用 WebSocket 的 close 方法
      player.destroy
      player.destroy()
    }
    player = null;
  }
});

function getVideos() {
  const canvas = jsmpegCanvas.value
  if (canvas) {
    const url = 'ws://127.0.0.1:8866/live?index=194&js=jsmpeg'
    try {
      player = new window.JSMpeg.Player(url, { canvas })
    } catch (error) {
      console.error('创建播放器JSmpeg失败:', error)
    }
  } else {
    console.error('Canvas元素未找到')
  }
}

function togglePlayPause() {
  if (player) {
    if (player.paused) {
      player.play() // 播放
      isPaused.value = false
    } else {
      player.pause() // 暂停
      isPaused.value = true
    }
  }
}

// 音量控制函数
function setVolume() {
  if (player) {
    player.volume = volume.value // 设置音量
  }
}

function destroyT(){
    player.destroy()
    player.source.socket.readyState
}
// 格式化播放进度
const formattedDuration = computed(() => {
  return formatDuration(duration.value)
})
</script>

<style scoped></style>
I can use your method to stop the video playback and destroy the video instance. But WebSocket was not interrupted.

**Comment by phoboslab** [comment] 2024-12-03 09:28
readyState 2 is `WebSocket.CLOSING`. A short time later it should transition to `WebSocket.CLOSED`. See https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState)

**Comment by zhang22113** [comment] 2024-12-03 09:37
> readyState 2 为`WebSocket.CLOSING`。 不久之后它应该会转换为`WebSocket.CLOSED`。 请参阅[https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState)](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState%5D(https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState))

The problem lies here, I have been waiting, but it has not been closed. Even if I close my browser, the websocket connection remains open.

**Comment by phoboslab** [comment] 2024-12-03 09:43
I don't understand. If it was open, readyState would be `1`. If it remains in `CLOSING` state (and does not transition to `CLOSED`), maybe your WebSocket server is not correctly handling the close message? It should timeout after 30sec, though (depending on the browser).

I'm sorry, but I will not provide any further assistance here. This does not seem to be a problem with JSMpeg itself.

**Closed as completed** 2024-12-03 09:43 UTC
